;; DO NOT EDIT THIS FILE!
;; It is autogenerated by `i18n.create-artifacts` as part of the release process.
{:locales
 #{"ar"
   "ar-SA"
   "bg"
   "ca"
   "cs"
   "de"
   "en"
<<<<<<< HEAD
   "sq"
   "lv"
   "ar-SA"
   "zh"
   "sr"
   "tr"
   "it"
=======
   "es"
>>>>>>> v1.49.0
   "fa"
   "fi"
   "fr"
   "he"
   "id"
   "it"
   "ja"
   "ko"
   "lv"
   "nb"
   "nl"
   "pl"
   "pt-BR"
<<<<<<< HEAD
   "zh-CN"
   "de"
   "nb"
   "ru"
   "sk"
   "es"
   "ja"
   "cs"
   "ar"
   "bg"
   "ko"},
=======
   "ru"
   "sk"
   "sq"
   "sr"
   "sv"
   "tr"
   "uk"
   "vi"
   "zh"
   "zh-CN"
   "zh-HK"
   "zh-TW"},
>>>>>>> v1.49.0
 :packages ["metabase"],
 :bundle "metabase.Messages"}
